language: python
python:
    - "2.7"

sudo: required

install:
    - cd ..
    - git clone https://github.com/Sayo-nika/BraveSail --depth=50

env:

    - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy

script:  ls && ./autobuild.sh/autobuild.sh -d BraveSail && ls BraveSail/build 
